### ISSUE TITLE
3.7.0 to pypi?

### ISSUE THREAD

**Issue by dwasyl** [jazzband/django-cities-light#228]
Hey there,

Glad to see 3.7.0 has a fix for the subregion issue, any chance this version can get pushed to pypi?

Thanks!

**Comment by marianoeramirez** [comment]
Update, 

I am requesting for help to jazzband-roadies to see if they can help to configure the pipeline job to finish with the auto-deploy, Here is the ticket if you want to support the request, jazzband-roadies/help#199.

We already have the process https://travis-ci.org/github/jazzband/django-cities-light/jobs/722731202, Just need some configuration from JazzBand.

**Comment by SanketDG** [comment]
@marianoeramirez What do you think about forking this and publishing with a different package name like `django-cities-lite`?

**Comment by marianoeramirez** [comment]
I am thinking the same, but waiting to see if @jpic or some from Jazzband take any action first.

**Comment by cristiangrojas** [comment]
By now, is it possible to install the latest version via pip install somehow?

**Comment by marianoeramirez** [comment]
@cristiangrojas 
You can use this command to install using pip:

`pip install git+https://github.com/jazzband/django-cities-light.git`

**Comment by jpic** [comment]
@marianoeramirez accept the invite on pypi to manage django-cities-light then you can make releases.

Meanwhile, I uploaded 3.7.0.

**Comment by marianoeramirez** [comment]
ok, @jpic thanks, done. I accepted the invitation. 

I close this ticket and will release today the version 3.8.0 too.

**Comment by jpic** [comment]
Thanks for the notification, I promoted you to Owner in Pypi so that you
can setup automatic CI.

There are probably some github actions, you can probably have something
like what we have in gitlab on new packages:

```
pypi-job:
  only: [tags]
  image: yourlabs/python
  script: pypi-release
```

It just needs TWINE environment variables TWINE_USERNAME and TWINE_PASSWORD

Otherwise, copy the script from there:
https://yourlabs.io/oss/containers/-/blob/master/python/bin/pypi-release

You can use zsimic/setupmeta for automatic version from tag in setup.py,
otherwise put a marker in setup.py and use sed ^^

Keep up the great work
